version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - api

  api:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - '3001:3001'